### Today's Contents

-   Introduction
-   Data types
-   Loops
-   Conditional statements
-   Functions
-   NumPy
-   Plotting using Matplotlib
-   Pandas

### Introduction

*   Developed by Guido van Rossum
*   first released in 1991
*   simple to read (close to plain English)
*   simple to code (intuitive)
*   interpreted (no compilation)
*   high-level (no machine code)
*   general purpose language (can be used for anything)
*   open source ([361,832 fellow developers and contributors in the community supporting 266,966 packages of Python](https://analyticsindiamag.com/top-10-python-packages-with-most-contributors-on-github/).)
* source code available at: https://github.com/python/cpython



**Sources**

Many sources are available online, libraries documentations, online courses, books, websites offering free tutorials. 

The following are links for books that are freely available online:
1. [Python Data Science Handbook, Jake VanderPlas, O'Reilly, First Edition 2016](https://tanthiamhuat.files.wordpress.com/2018/04/pythondatasciencehandbook.pdf)
2. [Fluent Python, Luciano Ramalho, O'Reilly, First Edition 2015](http://index-of.es/Varios-2/Fluent%20Python%20Clear%20Concise%20and%20Effective%20Programming.pdf)

**Installation**

Easiest way to start working on Python is to downlaod the [Anaconda IDE](https://www.anaconda.com/products/individual).

*   Spyder
*   JupyterLab / Jupyter Notebook

You are looking at Jupyter notebook right now.

**Print > Hello World**

In [1]:
print('Hello World!!')

Hello World!!


**Python is case sensitive.**

In [2]:
Print('Hello World')

NameError: name 'Print' is not defined

In [3]:
kiko = 6

In [4]:
 kiko # Kiko is not defined

6

**Variables names**

In [5]:
kiko@ = 6   # special characters in variables names

SyntaxError: invalid syntax (Temp/ipykernel_4936/2161889285.py, line 1)

In [6]:
and = 5+6    # invalid variable name - or, return, import, ...

SyntaxError: invalid syntax (Temp/ipykernel_4936/2353299279.py, line 1)

### Data types

*   Integer
*   Float
*   String
*   Boolean
*   List




**Boolean**

In [7]:
print(3>1)

True


In [8]:
print(1 == 3)

False


In [9]:
z = True

In [10]:
type(z)

bool

In [11]:
if z == False:
  print("z is False")
else: 
  print("z is True")

z is True


In [12]:
g = 3>2

In [13]:
g

True

In [14]:
type(g)

bool

**Integers**

In [15]:
x = 3

In [16]:
x**2

9

In [17]:
type(x)

int

**Float**

In [18]:
xf = 3.3

In [19]:
type(xf)

float

**String**

In [20]:
myName = "Mohamed Labib"

In [21]:
type(myName)

str

**Printing different variables**

In [26]:
print('x is equal to {}' .format(x,2))    # repeat with float, show rounding

x is equal to 89.9562


In [27]:
x = 89.9562
x

89.9562

**Converting variables types**

In [28]:
n = str(x)

In [29]:
n

'89.9562'

In [30]:
print('x is equal to', n)

x is equal to 89.9562


In [31]:
y = float(n)

In [32]:
type(y)

float

In [33]:
type(n)    # n remains as string

str

In [34]:
x = int(y)

In [35]:
type(x)

int

In [36]:
x   # no rounding

89

**List**

In [37]:
a = [1.13, 'hello', 56, 'r']    # a list can contain values of different data types

In [40]:
a[0:3]    # indexing and slicing

[1.13, 'hello', 56]

Different functions and applications can be used using lists. List is one of Python's four collection data types (others are [Tuple](https://www.w3schools.com/python/python_tuples.asp), [Set](https://www.w3schools.com/python/python_sets.asp) and [Dictionary](https://www.w3schools.com/python/python_dictionaries.asp)). We recommend you check the provided links if you are interested to learn about these data types.

**Arithmetic operations**

In [41]:
o = 5*5    # for multiplication use *
o

25

In [42]:
o = 3/4   # for division: /
o

0.75

In [43]:
o = 3%4    # for remainder use %
o

3

In [44]:
o**3    # for power use **

27

Special mathematical functions (```sin```, ```cos```, ```sqrt```, ..) can be used from the ```math``` library.


**```for``` and ```while``` loops**



In [45]:
i = 0
while i <= 5:
    p = i + 2    # do something
    print(p)
    i += 1       # increment i by 1 (Avoid infinte loops!)

2
3
4
5
6
7


In [46]:
for i in myName: 
    print(i)

M
o
h
a
m
e
d
 
L
a
b
i
b


In [53]:
for i in 'Ahmad657':    # applicable on the string directly
    print(i)

A
h
m
a
d
6
5
7


In [54]:
myName[0:4]    # indexing and slicing 

'Moha'

In [57]:
for i in range(3,9):    # from first to second argument excluding the second argument
    print(i)

3
4
5
6
7
8


In [58]:
for i in range(3):    # default start from 0
    for j in range(4):
        print(j)

0
1
2
3
0
1
2
3
0
1
2
3


**Exercise 1**

Write a code to produce the following result.

1 x 0 = 0
<br>
1 x 1 = 1
<br>
1 x 2 = 2
<br>
1 x 3 = 3
<br>
1 x 4 = 4
<br>
2 x 0 = 0
<br>
2 x 1 = 2
<br>
2 x 2 = 4
<br>
2 x 3 = 6
<br>
2 x 4 = 8
<br>
3 x 0 = 0
<br>
3 x 1 = 3
<br>
3 x 2 = 6
<br>
3 x 3 = 9
<br>
3 x 4 = 12
<br>
4 x 0 = 0
<br>
4 x 1 = 4
<br>
4 x 2 = 8
<br>
4 x 3 = 12
<br>
4 x 4 = 16
<br>
5 x 0 = 0
<br>
5 x 1 = 5
<br>
5 x 2 = 10
<br>
5 x 3 = 15
<br>
5 x 4 = 20

**Input from user**

In [62]:
mynum = input('Enter a number: ') 

Enter a number:  23


In [70]:
mynum

23

In [71]:
type(mynum)   # conversion needed depending on usage in code

int

### Conditional statements: ```if```, ```elif``` and ```else```

In [74]:
if 'M' in "Mango":
    print('M in mango')
else:
    print('no Ps')

M in mango


In [79]:
x = 13
y = 15

In [80]:
if x > y:
    print('x > y')
elif x == y:
    print('x = y')
else:
    print('x < y')

x < y


In [81]:
if x >= y:    
    print('x >= y')
elif x <= y:     # incorrect - if equal then will be executed at first line
    print('x <= y')
else:
    print('Error')

x <= y


In [82]:
z = 5

In [83]:
if (x > y or x < y) and (x > z):      # remove ```and (x > z) for or operation alone
    print("x and y are not equal and x is larger than z")
else:
    print("x and y are equal")

x and y are not equal and x is larger than z


**Exercise 2**

Build a calculator that takes 2 integers from the user and a mathematical sign (+, -, *, /), then does the operation. Print an error message for division by zero.

### Functions

In [84]:
x = 5
y = 6
z = x + y
z

11

In [89]:
def addsum(x, y): # can add more input arguments
    return x + y   # can add more returns

In [90]:
z, d = addsum(5,6)    # assign the return value to a varibale z, another way: addsum(x=5, y=6)
# print('d= ', d)       # can be printed directly from the function too
print('z = ', z) 

d=  -1
z =  11


**Exercise 3**

Repeat the last calculator exercise using a function that takes as arguments the three inputs. Try by calling the function. No user input.

**Exercise 4**

Write a function that takes two numbers as input, and return the values of the sum, difference, multiplication and division of both numbers. Assign the return values to four different variables when calling the function.

### NumPy

NumPy is a Python library, used for working with numerical arrays.

In [91]:
import numpy as np

In [95]:
d1 = np.arange(1,10,1)    # creates a 1-d array with values from 1 to 9 with a step of 1
                          # can be for floats as well, try a less step
d1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [96]:
type(d1)

numpy.ndarray

ndarray > n-dimensional array. ```d1``` is a 1-dimensional array.

In [97]:
len(d1)    # provides the length of the array

9

In [98]:
np.shape(d1)    # provides the shape of the array

(9,)

**Exercise 5**

Create a for loop to print all the values in ```d1```.

In [130]:
v = np.linspace(1,10,10)   # creates a 1-d array, with a range from 1 to 10, equally spaced values, with length 10
v

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [100]:
len(v)

10

In [101]:
type(v)

numpy.ndarray

In [103]:
vreshape = np.reshape(v,(2,5))    # creates a 2-d matrix 'vreshape' with same values of v but arranged in 2 rows and 5 columns
vreshape

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.]])

In [104]:
vnew = np.array([                 # creates a 2-d matrix with the given values
    [1,2,3],
    [9,-8,7],
    [5,1,6]
])
vnew

array([[ 1,  2,  3],
       [ 9, -8,  7],
       [ 5,  1,  6]])

In [105]:
np.shape(vnew)

(3, 3)

**Indexing and slicing**

In [108]:
vnew[2,2]   

6

**Mathematical functions**

In [109]:
np.mean(vnew)   # returns vnew's mean value

2.888888888888889

In [110]:
np.sum(vnew)    # returns vnew's sum value

26

In [111]:
np.max(vnew)    # returns vnew's max value

9

In [112]:
np.argmax(vnew)    # returns vnew's index of max value

3

In [124]:
xzero = np.zeros([4,3])
# xzero[2,2]=3    # assign values to definite locations
xzero

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [125]:
xone = np.ones([4,3])
# xone[1,2]=5     
xone

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [122]:
xzo = xzero + xone    # element-wise operation
xzo

array([[1., 1., 1.],
       [1., 1., 5.],
       [1., 1., 4.],
       [1., 1., 1.]])

**Note:** Cross and dot products are available through ```numpy.dot()``` and ```numpy.cross()``` functions.

In [22]:
xzo

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [23]:
xzo[1:3,1] = 5

In [24]:
xzo

array([[1., 1., 1.],
       [1., 5., 1.],
       [1., 5., 1.],
       [1., 1., 1.]])

In [25]:
len(xzo)    # returns the number of rows or np.shape(xzo)[0]

4

In [127]:
np.shape(xzo)[1]    # returns the number of columns

3

In [128]:
# create random array:
a = np.random.randint(-10,10,(3,4))
print(a)

[[ 9 -7 -7 -5]
 [-1 -7  1  6]
 [-2  1 -3 -5]]


For more on `numpy.random()` check the available [documentation](https://numpy.org/doc/1.16/reference/routines.random.html).

**Exercise 6**

Calculate the dot product (manually using for loops) of matrices A and B and store them in a matrix `C`. 

\begin{equation*}
A = 
\begin{pmatrix}
1 & 2 \\
4 & 5
\end{pmatrix}
\end{equation*}
       
\begin{equation*}
B = 
\begin{pmatrix}
9 & 8 \\
6 & 5 
\end{pmatrix}
\end{equation*}

**Plotting using Matplotlib**

In [144]:
xplt = np.linspace(-np.pi,np.pi,30)    # an array values from -pi to pi, length = 30

In [145]:
yplt = xplt**2
yplt_sc = yplt + np.random.normal(-0.3, 0.3, 30)

In [146]:
import matplotlib.pyplot as plt

In [147]:
# %matplotlib widget

In [148]:
plt.plot(xplt,yplt_sc,'o', xplt, yplt, '-')
plt.xlabel('x')
plt.ylabel('y')
plt.title('Relation of x and y')
plt.legend(['Data points', 'Model'], loc='best')
plt.show()

**Another way - Object oriented**

In [149]:
fig, ax = plt.subplots()
ax.plot(xplt, yplt_sc,'o', xplt, yplt, '-')
ax.set(xlabel='xplt', ylabel='yplt', title = 'Relation of x and y')
ax.legend(['Data points', 'Model'], loc='best')
plt.show()

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

**Subplots**

In [141]:
# display 4 plots in one figure
fig, axs = plt.subplots(nrows=2, ncols=2, figsize=(16,10))          # specifies the number of rows and columns, and figure size
axs[0,0].plot(xplt, xplt**2)                                        # specifies to plot in row 0 column 0
axs[0,0].set(xlabel='x', ylabel='$f(x)$', title = '$f(x) = x^2$')
axs[0,1].plot(xplt, np.sin(xplt))
axs[0,1].set(xlabel='x', ylabel='$f(x)$', title = '$f(x) = sin(x)$')
axs[1,0].plot(xplt, np.cos(xplt))
axs[1,0].set(xlabel='x', ylabel='$f(x)$', title = '$f(x) = cos(x)$')
axs[1,1].plot(xplt, np.tan(xplt))
axs[1,1].set(xlabel='x', ylabel='$f(x)$', title = '$f(x) = tan(x)$')
plt.show()

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

**Note:** check different types of plots available in `matplotlib` library's [Gallery page](https://matplotlib.org/stable/gallery/index.html).

### Pandas

Pandas is essential for dealing with data. It is built on top of NumPy. Available data structures are the Series and DataFrame. A series is a 1 dimensional array of data (can hold different data types) with an index. 

In [150]:
import pandas as pd

**Series**

In [151]:
a = pd.Series([0.3,11.1,4.3,'43.2',5,20.2])     #can hold different data types in one series
a

0     0.3
1    11.1
2     4.3
3    43.2
4       5
5    20.2
dtype: object

In [154]:
type(a)   # check type of a 

pandas.core.series.Series

In [155]:
type(a[3])    # check type of any value in a using its index

str

In [159]:
a[1:3]    # slicing 

1    11.1
2     4.3
dtype: object

**DataFrame**

A DataFrame is a multi-dimensional array of different data types. 

In [160]:
df = pd.DataFrame(np.random.randint(-10,10,[4,4]), columns = ['A', 'B', 'C', 'D'])

In [161]:
df

A  B  C  D
0  9 -4  7 -1
1 -3  6  1  5
2 -6  3  7 -5
3 -7 -5  9  7

In [162]:
df['E'] = np.random.randint(-10,10,[4,1])   # add column E

In [163]:
df

A  B  C  D  E
0  9 -4  7 -1 -2
1 -3  6  1  5 -9
2 -6  3  7 -5  2
3 -7 -5  9  7 -3

In [164]:
# add new row
df1 = pd.DataFrame(np.random.randint(-10,10,[1,5]), columns = ['A', 'B', 'C', 'D', 'E'])

In [165]:
df = df.append(df1, ignore_index = True)    # adds a new row to df

In [166]:
df

A  B  C  D  E
0  9 -4  7 -1 -2
1 -3  6  1  5 -9
2 -6  3  7 -5  2
3 -7 -5  9  7 -3
4  9 -9 -4  4  5

**Indexing and Slicing**

In [167]:
df[['A','C']]    # call by column names

A  C
0  9  7
1 -3  1
2 -6  7
3 -7  9
4  9 -4

In [169]:
df.iloc[3,2]    # value in row 3 and column 4

9

In [170]:
df.iloc[:,3:5]    # = df[['D','E']]  all rows columns 3 and 4

D  E
0 -1 -2
1  5 -9
2 -5  2
3  7 -3
4  4  5

In [171]:
df.iloc[1:3,3:5] = [[4, 'nan'],['NaN', 89]]    # change values in df
df

A  B  C    D    E
0  9 -4  7   -1   -2
1 -3  6  1    4  nan
2 -6  3  7  NaN   89
3 -7 -5  9    7   -3
4  9 -9 -4    4    5

In [172]:
df['names'] = ['row0', 'row1', 'row2', 'row3', 'row4']    # add column 'names'

In [173]:
df

A  B  C    D    E names
0  9 -4  7   -1   -2  row0
1 -3  6  1    4  nan  row1
2 -6  3  7  NaN   89  row2
3 -7 -5  9    7   -3  row3
4  9 -9 -4    4    5  row4

In [174]:
df = df.set_index('names')    # set column 'names' as df's index
df

A  B  C    D    E
names                   
row0   9 -4  7   -1   -2
row1  -3  6  1    4  nan
row2  -6  3  7  NaN   89
row3  -7 -5  9    7   -3
row4   9 -9 -4    4    5

In [177]:
df.loc["row2"]    # df.loc[] not df.iloc[], for usage with labels, can add column label too

A     -6
B      3
C      7
D    NaN
E     89
Name: row2, dtype: object

In [179]:
df.to_csv("test2")    # create a csv file with df values in the same notebook directory 

In [182]:
df = pd.read_csv("test2", index_col='names')     #index_col to specify index, check function's documentation for other useful input arguments

In [183]:
df

A  B  C    D     E
names                    
row0   9 -4  7 -1.0  -2.0
row1  -3  6  1  4.0   NaN
row2  -6  3  7  NaN  89.0
row3  -7 -5  9  7.0  -3.0
row4   9 -9 -4  4.0   5.0

**Exercise 7**

Import "Grades.csv" assign column ID as the index of your DataFrame. 
1. Assign the data for student with ID 6104062 to a variable `student`.
2. Print the data type of `student`.
3. Print the name of `student`.
4. Change the 'Mathematics' and 'English' grades to 38 and 39 for student 6104065, and 45 and 43 for student 6104067.
5. For all students:
    -  Print all the data excluding the 'Name' column.
    -  Add column `Total [%]`. The values in `Total [%]` are equal to the overall grade percentage (assuming each subject is 50 marks).

**Arithmetic Operations**

In [69]:
maxGrade = grades['Total [%]'].max() # same for mean, min, count, sum, std, ..
maxGrade

90.67

**Conditional statements**

In [70]:
grades.loc[grades['Total [%]'] <= 75]   # also can be done specifying a row and a column > add ", 'Class'"

Class  Mathematics  English  Physics  Total [%]
ID                                                     
6104066     B           26       44       37      71.33

In [71]:
grades[grades['Total [%]'] >= 85]

Class  Mathematics  English  Physics  Total [%]
ID                                                     
6104060     A           46       42       48      90.67
6104061     A           42       45       41      85.33
6104064     B           43       45       47      90.00
6104067     A           45       43       46      89.33

In [72]:
grades[(grades['Total [%]'] < 85) & (grades['Total [%]'] > 75)]    # for or use |

Class  Mathematics  English  Physics  Total [%]
ID                                                     
6104062     B           39       36       42      78.00
6104063     A           46       41       35      81.33
6104065     B           38       39       38      76.67

**Exercise 8**

- Print students who scored less than 30 marks in any of the subjects.
- Print the highest score for each subject.
- Print the students with the highest subject grade.

**Grouping**

In [ ]:
grouped = grades.groupby('Class')    # create groups from the dataframe grades, based on the 'Class' column

In [ ]:
grouped

In [ ]:
grouped["Total [%]"].max()

In [ ]:
ClassA = grouped.get_group("A")    # assign Class A students to variable (DataFrame) Class A
ClassA

In [ ]:
type(ClassA)    # Class A is now a separate DataFrame

**Exercise 9**

Create a bar chart for each class in one figure. The chart shall contain grades of the three subjects and total percentage for each student. Search Google, different plotting methods are acceptable.